import { chromium } from '@playwright/test';
const BASE = process.env.DEMO_BASE_URL ?? 'http://localhost:3001';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 }, storageState: 'demo-out/auth-state.json' });
const page = await ctx.newPage();
await page.goto(BASE + '/');
await page.waitForTimeout(3500);
await page.getByRole('button', { name: /^Files/ }).first().click();
await page.waitForTimeout(1500);
console.log('copy buttons:', await page.locator('[title="Copy code"]').count());
console.log('show-all buttons:', await page.getByRole('button', { name: /show all \d+ lines/i }).count());
console.log('preview tabs:', await page.getByRole('button', { name: /^Preview$/ }).count());
console.log('iframes:', await page.locator('iframe').count());
console.log('drawer buttons:', await page.getByRole('button', { name: /open in drawer/i }).count());
console.log('platform chips:', await page.locator('[title^="Coding-agent platform"]').allInnerTexts().catch(() => []));
await page.screenshot({ path: 'demo-out/s07-files-tab.png' });
const frame = page.frameLocator('iframe').first();
const toggle = frame.locator('text=/annual|yearly|年付|年/i').first();
console.log('toggle in iframe:', await toggle.count().catch(() => 'frame err'));
await browser.close();
